version: '3.3'

services:

#################################################### Base images
    base:
      build:
        context: ../src/BaseOS/
      image: ubuntu:base

    conda:
      build:
        context: ../src/conda/
      image: ubuntu:conda

    bowtie:
      build:
        context: ../src/contextmap2/bowtie/
      image: bowtie:0.1

#################################################### Mapping tools
    star:
      build:
        context: ../src/Star
      image: proj/star:0.01

    bbmap:
      build:
        context: ../src/BBMap
      image: proj/bbmap:0.01


    contextmap2:
      build:
        context: ../src/contextmap2
      image: proj/contextmap:0.01


    dart:
      build:
        context: ../src/dart
      image: proj/dart:0.01


    gsnap:
      build:
        context: ../src/gsnap
      image: proj/gsnap:0.01


    crac:
      build:
        context: ../src/crac
      image: proj/crac:0.01


    subjunc:
      build:
        context: ../src/subjunc
      image: proj/subjunc:0.01


    minimap:
      build:
        context: ../src/minimap2
      image: proj/minimap2:0.01


    hisat2:
      build:
        context: ../src/hisat2
      image: proj/hisat2:0.01


    segemehl:
      build:
        context: ../src/segemehl
      image: proj/segemehl:0.01


    mapsplice2:
      build:
        context: ../src/mapsplice2
      image: proj/mapsplice2:0.01


######################################################### AS event detection tools

# ONLY BUILDS ON DOCKER 19
#    asgal:
#      build:
#        context: ../src/asgal/
#      image: proj/asgal:0.01

#    cash:
#      build:
#        context: ../src/CASH/
#      image: proj/cash:0.01
      
    majiq:
      build: 
        context: ../src/MAJIQ/
      image: proj/majiq:0.01

    spladder:
      build: 
        context: ../src/spladder/
      image: proj/spladder:0.01      

    aspli:
      build: 
        context: ../src/ASpli/
      image: proj/aspli:0.01      

    eventpointer:
      build: 
        context: ../src/EventPointer/
      image: proj/eventpointer:0.01

    kissplice:
      build: 
        context: ../src/KisSplice/
      image: proj/kissplice:0.01

    whippet:
      build: 
        context: ../src/Whippet/
      image: proj/whippet:0.01

    sgseq:
      build: 
        context: ../src/SGSeq/
      image: proj/sgseq:0.01

    irfinder:
      build: 
        context: ../src/irfinder/
      image: proj/irfinder:0.01



#### Diff Splicing tools
#    :
#      build: 
#        context: ../src//
#      image: proj/:0.01
#       dockerfile: Dockerfile
        


######################################################### AS diff tools

    rmats:
      build: 
        context: ../src/rMATS/
      image: proj/rmats:0.01


    dsplicetype:
      build: 
        context: ../src/dSpliceType/
      image: proj/dsplicetype:0.01

    psisigma:
      build: 
        context: ../src/PSI-Sigma/
      image: proj/psisigma:0.01

    leafcutter:
      build: 
        context: ../src/leafcutter/
      image: proj/leafcutter:0.01


#    jum:
#      build: 
#        context: ../src/JUM/
#      image: proj/jum:0.01
