version: '3.3'

services:

#################################################### Base images
    base:
      build:
        context: ../BaseOS/
      image: ubuntu:base

    conda:
      build:
        context: ../conda/
      image: ubuntu:conda

    bowtie:
      build:
        context: ../contextmap2/bowtie/
      image: bowtie:0.1

#################################################### Mapping tools
    star:
      build:
        context: ../Star
      image: proj/star:0.01

# ONLY BUILDS ON DOCKER 19
#    asgal:
#      build:
#        context: ../asgal/
#      image: proj/asgal:0.01


    bbmap:
      build:
        context: ../BBMap
      image: proj/bbmap:0.01


    contextmap2:
      build:
        context: ../contextmap2
      image: proj/contextmap:0.01


    dart:
      build:
        context: ../dart
      image: proj/dart:0.01


    gsnap:
      build:
        context: ../gsnap
      image: proj/gsnap:0.01


    crac:
      build:
        context: ../crac
      image: proj/crac:0.01


    subjunc:
      build:
        context: ../subjunc
      image: proj/subjunc:0.01


    minimap:
      build:
        context: ../minimap2
      image: proj/minimap2:0.01


    hisat2:
      build:
        context: ../hisat2
      image: proj/hisat2:0.01


    segemehl:
      build:
        context: ../segemehl
      image: proj/segemehl:0.01


    mapsplice2:
      build:
        context: ../mapsplice2
      image: proj/mapsplice2:0.01


######################################################### AS event detection tools
  #  cash:
  #    build:
  #      context: ../CASH/
  #      image: proj/cash:0.01
  #      dockerfile: Dockerfile



######################################################### AS diff tools
