version: '3.3'

services:

#################################################### Base images
    base:
      build:
        context: ../src/BASE-IMAGE/
      image: ubuntu:base

    conda:
      build:
        context: ../src/conda/
      image: ubuntu:conda

    bowtie:
      build:
        context: ../src/contextmap2/bowtie/
      image: bowtie:0.1

#################################################### Mapping tools
    star:
      build:
        context: ../src/star
      image: dicast/0.01:star

    bbmap:
      build:
        context: ../src/bbmap
      image: dicast/0.01:bbmap


    contextmap2:
      build:
        context: ../src/contextmap
      image: dicast/0.01:contextmap


    dart:
      build:
        context: ../src/dart
      image: dicast/0.01:dart


    gsnap:
      build:
        context: ../src/gsnap
      image: dicast/0.01:gsnap


    crac:
      build:
        context: ../src/crac
      image: dicast/0.01:crac


    subjunc:
      build:
        context: ../src/subjunc
      image: dicast/0.01:subjunc


    minimap:
      build:
        context: ../src/minimap
      image: dicast/0.01:minimap2


    hisat2:
      build:
        context: ../src/hisat
      image: dicast/0.01:hisat2


    segemehl:
      build:
        context: ../src/segemehl
      image: dicast/0.01:segemehl


    mapsplice2:
      build:
        context: ../src/mapsplice
      image: dicast/0.01:mapsplice2


######################################################### AS event detection tools

# ONLY BUILDS ON DOCKER 19
#    asgal:
#      build:
#        context: ../src/asgal/
#      image: dicast/0.01:asgal

#    cash:
#      build:
#        context: ../src/cash/
#      image: dicast/0.01:cash
      
    majiq:
      build: 
        context: ../src/majiq/
      image: dicast/0.01:majiq

    spladder:
      build: 
        context: ../src/spladder/
      image: dicast/0.01:spladder      

    aspli:
      build: 
        context: ../src/aspli/
      image: dicast/0.01:aspli      

    eventpointer:
      build: 
        context: ../src/eventpointer/
      image: dicast/0.01:eventpointer

    kissplice:
      build: 
        context: ../src/kissplice/
      image: dicast/0.01:kissplice

    whippet:
      build: 
        context: ../src/whippet/
      image: dicast/0.01:whippet

    sgseq:
      build: 
        context: ../src/sgseq/
      image: dicast/0.01:sgseq

    irfinder:
      build: 
        context: ../src/irfinder/
      image: dicast/0.01:irfinder



#### Diff Splicing tools
#    :
#      build: 
#        context: ../src//
#      image: dicast/0.01:
#       dockerfile: Dockerfile
        


######################################################### AS diff tools

    rmats:
      build: 
        context: ../src/rmats/
      image: dicast/0.01:rmats


    dsplicetype:
      build: 
        context: ../src/dsplicetype/
      image: dicast/0.01:dsplicetype

    psisigma:
      build: 
        context: ../src/psisigma/
      image: dicast/0.01:psisigma

    leafcutter:
      build: 
        context: ../src/leafcutter/
      image: dicast/0.01:leafcutter


#    jum:
#      build: 
#        context: ../src/jum/
#      image: dicast/0.01:jum
