version: '3.3'

services:

#################################################### Base images
    base:
      build:
        context: ../../src/BASE-IMAGE/
      image: gitlab.lrz.de:5005/ge46ban/dockers/develop/base:0.1

    conda:
      build:
        context: ../../src/conda/
      image: gitlab.lrz.de:5005/ge46ban/dockers/develop/base-conda:0.1

    bowtie:
      build:
        context: ../../src/bowtie/
      image: gitlab.lrz.de:5005/ge46ban/dockers/develop/dicast-bowtie:0.1

#################################################### Mapping tools
    star:
      build:
        context: ../../src/star
      image: gitlab.lrz.de:5005/ge46ban/dockers/develop/star:0.1

    bbmap:
      build:
        context: ../../src/bbmap
      image: gitlab.lrz.de:5005/ge46ban/dockers/develop/bbmap:0.1


    contextmap2:
      build:
        context: ../../src/contextmap
      image: gitlab.lrz.de:5005/ge46ban/dockers/develop/contextmap:0.1


    dart:
      build:
        context: ../../src/dart
      image: gitlab.lrz.de:5005/ge46ban/dockers/develop/dart:0.1


    gsnap:
      build:
        context: ../../src/gsnap
      image: gitlab.lrz.de:5005/ge46ban/dockers/develop/gsnap:0.1


    crac:
      build:
        context: ../../src/crac
      image: gitlab.lrz.de:5005/ge46ban/dockers/develop/crac:0.1


    subjunc:
      build:
        context: ../../src/subjunc
      image: gitlab.lrz.de:5005/ge46ban/dockers/develop/subjunc:0.1


    minimap:
      build:
        context: ../../src/minimap
      image: gitlab.lrz.de:5005/ge46ban/dockers/develop/minimap2:0.1


    hisat2:
      build:
        context: ../../src/hisat
      image: gitlab.lrz.de:5005/ge46ban/dockers/develop/hisat2:0.1


    segemehl:
      build:
        context: ../../src/segemehl
      image: gitlab.lrz.de:5005/ge46ban/dockers/develop/segemehl:0.1


    mapsplice2:
      build:
        context: ../../src/mapsplice
      image: gitlab.lrz.de:5005/ge46ban/dockers/develop/mapsplice2:0.1


######################################################### AS event detection tools

# ONLY BUILDS ON DOCKER 19
    asgal:
      build:
        context: ../../src/asgal/
      image: gitlab.lrz.de:5005/ge46ban/dockers/develop/asgal:0.1

#    cash:
#      build:
#        context: ../../src/cash/
#      image: gitlab.lrz.de:5005/ge46ban/dockers/develop/cash:0.1
      
    majiq:
      build: 
        context: ../../src/majiq/
      image: gitlab.lrz.de:5005/ge46ban/dockers/develop/majiq:0.1

    spladder:
      build: 
        context: ../../src/spladder/
      image: gitlab.lrz.de:5005/ge46ban/dockers/develop/spladder:0.1    

    aspli:
      build: 
        context: ../../src/aspli/
      image: gitlab.lrz.de:5005/ge46ban/dockers/develop/aspli:0.1

    eventpointer:
      build: 
        context: ../../src/eventpointer/
      image: gitlab.lrz.de:5005/ge46ban/dockers/develop/eventpointer:0.1

    kissplice:
      build: 
        context: ../../src/kissplice/
      image: gitlab.lrz.de:5005/ge46ban/dockers/develop/kissplice:0.1

    whippet:
      build: 
        context: ../../src/whippet/
      image: gitlab.lrz.de:5005/ge46ban/dockers/develop/whippet:0.1

    sgseq:
      build: 
        context: ../../src/sgseq/
      image: gitlab.lrz.de:5005/ge46ban/dockers/develop/sgseq:0.1

    irfinder:
      build: 
        context: ../../src/irfinder/
      image: gitlab.lrz.de:5005/ge46ban/dockers/develop/irfinder:0.1



#### Diff Splicing tools
#    :
#      build: 
#        context: ../../src//
#      image: gitlab.lrz.de:5005/ge46ban/dockers/develop/ :0.1
#       dockerfile: Dockerfile
        


######################################################### AS diff tools

    rmats:
      build: 
        context: ../../src/rmats/
      image: gitlab.lrz.de:5005/ge46ban/dockers/develop/rmats:0.1


    dsplicetype:
      build: 
        context: ../../src/dsplicetype/
      image: gitlab.lrz.de:5005/ge46ban/dockers/develop/dsplicetype:0.1

    psisigma:
      build: 
        context: ../../src/psisigma/
      image: gitlab.lrz.de:5005/ge46ban/dockers/develop/psisigma:0.1

    leafcutter:
      build: 
        context: ../../src/leafcutter/
      image: gitlab.lrz.de:5005/ge46ban/dockers/develop/leafcutter:0.1


#    jum:
#      build: 
#        context: ../../src/jum/
#      image: gitlab.lrz.de:5005/ge46ban/dockers/develop/jum:0.1
