#########################################
# When running the pipeline again with the same input file names or report name, the output will be also called the same and overwrite the existing files!
#
# Overwrite_acknowledge_choice__ = ["Yes", "No"]
Possible_overwrite_acknowledge:
    do: true

#########################################
# Do you want to run the ASimulatoR?    
#
# Start_ASimulatoR_with_run_choice__ = ["Yes", "No"]
ASimulatoR:
    do: True
#    ASimulatoR_config_directory: ../../scripts

#########################################
# Enter the name of the mapping tools you want to run as a space separated list.
#
# Currently we support bbmap, contextmap, crac, dart, gsnap, hisat, mapsplice, minimap, segemehl, star, subjunc
#
Mapping_tools:
    What_tools_to_run: 'bbmap contextmap crac dart gsnap hisat mapsplice minimap segemehl star subjunc'

#########################################
# Enter the name of the alternative splicing detection tools you want to run as a space separated list.
#
# Currently we support asgal, aspli, eventpointer, irfinder, majiq, sgseq, spladder, whippet
#
Alternative_splicing_detection_tools:
    What_tools_to_run: 'asgal aspli eventpointer irfinder majiq sgseq spladder whippet'

#########################################
# Snakemake creates a run report after finishing successfully. Here, you can set the file name (must end in .html!)
# You can also enter a full or relative path (e.g. output/snakemake/report.html).
#
# If you want to use the build-in "Open Report" button, you also have to set the parameter under # Option -> Preferences -> HTML page to open as a report. 
# The file name has to be the same as the config parameter.
#
Report:
    Report_file_name: dicast_snakemake_report.html
