---
title: "Data Analysis unified output"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---

R Notebook for comparison of 4 AS tools: Whippet, ASGAL, SplAdder and MAJIQ


functions and libraries
```{r}
library(ggplot2)
library(tidyr)
library(dplyr)
library(data.table)

read_file <- function(path, tool, strict, cutoff, mes, reads){
  
  tab <- read.csv(path)
  tab$precision <- as.numeric(tab$precision)
  tab$recall <- as.numeric(tab$recall)
  tab$tool <- rep(tool, 8)
  tab$mes <- rep(mes, 8)
  tab$strict <- rep(strict, 8)
  tab$cutoff <- rep(as.numeric(cutoff), 8)
  tab$reads <- rep(as.numeric(reads), 8)
  return(tab)
}

list_to_df <- function(list){
  dfs<-lapply(list, function(x){
    split <- base::strsplit(x, "/")
    mes <- split[[1]][1]
    reads <- split[[1]][2]
    file <- split[[1]][3]
    split2 <- base::strsplit(file, "_")
    tool <- split2[[1]][1]
    cutoff <- split2[[1]][2]
    strict <- base::strsplit(split2[[1]][3],"[.]")[[1]][1]
    df <- read_file(x, tool, strict, cutoff, mes, reads)
    return(df)
  })
  return (rbindlist(dfs))
}

# Multiple plot function
#
# ggplot objects can be passed in ..., or to plotlist (as a list of ggplot objects)
# - cols:   Number of columns in layout
# - layout: A matrix specifying the layout. If present, 'cols' is ignored.
#
# If the layout is something like matrix(c(1,2,3,3), nrow=2, byrow=TRUE),
# then plot 1 will go in the upper left, 2 will go in the upper right, and
# 3 will go all the way across the bottom.
#
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}
```


collect data and generate dataframes
```{r}
#setwd("~/Documents/Studium_Bioinformatik/Master/Semester3/FortgeschrittenenPrakitkum/unifyASOutputs/data/unified/")
c_50<-list.files("combined/50", pattern = "\\.stats.out$", full.names = T)
c_100<-list.files("combined/100", pattern = "\\.stats.out$", full.names = T)
c_200<-list.files("combined/200", pattern = "\\.stats.out$", full.names = T)

s_50<-list.files("separate/50", pattern = "\\.stats.out$", full.names = T)
s_100<-list.files("separate/100", pattern = "\\.stats.out$", full.names = T)
s_200<-list.files("separate/200", pattern = "\\.stats.out$", full.names = T)

files <- c(c_50, c_100, c_200, s_50, s_100, s_200)
data <- rbindlist(lapply(files, list_to_df))
data_no_zero <- subset(data, precision > 0.0 | recall > 0.0)
data_no_zero_long <- gather(data_no_zero, metric, score, precision:recall)

data_combined <- data_no_zero[data_no_zero$mes=="combined", ]
data_separate <- data_no_zero[data_no_zero$mes=="separate", ]
```


effect of combining MES, MEE and ES
```{r}
ggplot(data_no_zero[data_no_zero$cutoff == 0 & data_no_zero$strict=="loose" & data_no_zero$reads==50,])+
  geom_point(aes(x=precision, y=recall, color=tool, shape=type), size=4)+
  facet_grid(~mes)+
  scale_color_brewer(palette = "Set1")+
  scale_shape_manual(values=c(3,4,9,10,15,1,16,17))+
  ggtitle("Precision vs Recall per event type and tool")+
  theme_bw()
```


effect of sequencing depth
```{r}
p1<-ggplot(data_no_zero_long[data_no_zero_long$cutoff == 0 & data_no_zero_long$strict=="loose" & data_no_zero_long$mes == "separate",],aes(x=reads, y= score, color=tool))+
  geom_line(size=1, alpha=.7)+
  geom_point(shape=15,size=2)+
  facet_grid(type~metric)+
  ggtitle("A) precision and recall for each sequencing depth (separate approach)")+
  scale_color_brewer(palette = "Set1")+
  theme_bw()+
  scale_linetype_manual(values=c("solid", "dotted"))


p2<- ggplot(data_no_zero_long[data_no_zero_long$cutoff == 0 & data_no_zero_long$strict=="loose" & data_no_zero_long$mes == "combined",],aes(x=reads, y= score, color=tool))+
  geom_line(size=1, alpha=.7)+
  geom_point(shape=15,size=2)+
  facet_grid(type~metric)+
  ggtitle("B) precision and recall for each sequencing depth (combined approach)")+
  scale_color_brewer(palette = "Set1")+
  theme_bw()+
  scale_linetype_manual(values=c("solid", "dotted"))


multiplot(p1, p2)
```


```{r}
ggplot(data_no_zero[data_no_zero$reads == 50 & data_no_zero$mes=="combined" & data_no_zero$type !="ALE" & data_no_zero$type !="AFE" & data_no_zero$type !="MEE",], aes(x=strict, y=correct_events, fill=tool))+
  geom_bar(stat="identity", position="dodge")+
  facet_wrap(cutoff~type, scales = "free_y")+
  ggtitle("Number of correct event types for strict and loose comparison of events")+
  theme_bw()+  scale_color_brewer(palette = "Set1")
```



initial plots
```{r}
ggplot(data_combined, aes(x=precision, y=recall, color=tool, shape=type))+ 
  geom_point(size=3)+
  facet_grid(reads ~ strict)+
  scale_color_brewer(palette = "Set1")+
  ggtitle("Precision vs Recall split up by reads (horizontal) and strict \nor loose comparison of events (vertical)\n[combined MES, MEE and ES]")+
  scale_shape_manual(values=c(3,4,9,10,15,1,16,17))
```

```{r}
ggplot(data_separate, aes(x=precision, y=recall, color=tool, shape=type))+ 
  geom_point(size=3)+
  facet_grid(reads ~ strict)+
  scale_color_brewer(palette = "Set1")+
  ggtitle("Precision vs Recall split up by reads (horizontal) and strict \nor loose comparison of events (vertical)\n[separate MES, MEE and ES]")+
  scale_shape_manual(values=c(3,4,9,10,15,1,16,17))
```

